version: '3.4'

services:
  npvcalculator.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=52890
    ports:
      - "52890:80"

